import { 
  Organization, Role, Department, Location, Employee, Product, 
  Warehouse, Inventory, StockMovement, InventoryTransfer, Customer, 
  SalesOrder, SalesOrderItem, Supplier, PurchaseOrder, PurchaseOrderItem, 
  Delivery, SLA, Incident, IncidentComment, IncidentAssignment, 
  Approval, Workflow, WorkflowStep, Notification, AuditLog, EnterpriseMetric, Report 
} from '../types';

export const DEMO_ORG_ID = 'org-stratiq-001';

export const SEED_ORGANIZATION: Organization = {
  id: DEMO_ORG_ID,
  name: 'Apex Semiconductor & Global Robotics Ltd.',
  industry: 'Industrial Automation & High-Tech Manufacturing',
  logo_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=128&auto=format&fit=crop&q=80',
  created_at: '2025-01-01T00:00:00Z',
};

export const SEED_ROLES: Role[] = [
  {
    id: 'role-admin',
    code: 'ADMIN',
    name: 'Enterprise System Administrator',
    description: 'Full database, infrastructure, master entity management, and security permissions.',
    permissions: ['admin', 'admin:management', 'system:manage', 'all'],
  },
  {
    id: 'role-ceo',
    code: 'CEO',
    name: 'Chief Executive Officer',
    description: 'Full strategic oversight across organization, executive reports, cross-functional commands, and enterprise health.',
    permissions: ['executive:all', 'executive_override', 'reports:all', 'approvals:execute', 'incidents:view', 'dashboard:view', 'view_confidential'],
  },
  {
    id: 'role-coo',
    code: 'COO',
    name: 'Chief Operating Officer',
    description: 'Operations command, multi-site warehouse routing, supply chain coordination.',
    permissions: ['operations:all', 'inventory:transfer_override', 'incidents:escalate', 'approvals:execute'],
  },
  {
    id: 'role-cfo',
    code: 'CFO',
    name: 'Chief Financial Officer',
    description: 'Financial governance, budget approvals, procurement expenditure reviews.',
    permissions: ['finance:all', 'approvals:financial', 'reports:export', 'budgets:write'],
  },
  {
    id: 'role-operations-manager',
    code: 'OPERATIONS_MANAGER',
    name: 'Operations Manager',
    description: 'Incident resolution lead, SLA enforcement, active logistics dispatch.',
    permissions: ['incidents:manage', 'slas:assign', 'operations:dispatch', 'transfers:request'],
  },
  {
    id: 'role-inventory-manager',
    code: 'INVENTORY_MANAGER',
    name: 'Inventory Manager',
    description: 'Warehouse stock auditing, reorder automation, inter-facility transfers.',
    permissions: ['inventory:manage', 'transfers:manage', 'warehouses:view', 'stock:adjust'],
  },
  {
    id: 'role-procurement-manager',
    code: 'PROCUREMENT_MANAGER',
    name: 'Procurement Manager',
    description: 'Supplier relationship management, PO issuance, delivery schedule monitoring.',
    permissions: ['procurement:all', 'suppliers:manage', 'pos:create', 'deliveries:track'],
  },
  {
    id: 'role-hr-manager',
    code: 'HR_MANAGER',
    name: 'HR Manager',
    description: 'Workforce availability, shift rosters, departmental allocation.',
    permissions: ['workforce:manage', 'employees:view', 'shifts:allocate'],
  },
  {
    id: 'role-employee',
    code: 'EMPLOYEE',
    name: 'Operations Associate',
    description: 'Standard operational executor, task logger.',
    permissions: ['tasks:view', 'incidents:view_public'],
  },
];

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept-operations',
    organization_id: DEMO_ORG_ID,
    name: 'Global Operations',
    code: 'OPS',
    budget: 45000000,
    health_score: 72.4, // Lower due to active Pune delivery incident
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'dept-inventory',
    organization_id: DEMO_ORG_ID,
    name: 'Inventory & Warehousing',
    code: 'INV',
    budget: 68000000,
    health_score: 68.1,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'dept-procurement',
    organization_id: DEMO_ORG_ID,
    name: 'Procurement & Supply Chain',
    code: 'PROC',
    budget: 120000000,
    health_score: 74.5,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'dept-finance',
    organization_id: DEMO_ORG_ID,
    name: 'Finance & Capital',
    code: 'FIN',
    budget: 18000000,
    health_score: 96.0,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'dept-workforce',
    organization_id: DEMO_ORG_ID,
    name: 'Workforce & Talent',
    code: 'HR',
    budget: 24000000,
    health_score: 94.8,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'dept-sales',
    organization_id: DEMO_ORG_ID,
    name: 'Enterprise Sales & Fulfillment',
    code: 'SALES',
    budget: 35000000,
    health_score: 89.2,
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const SEED_LOCATIONS: Location[] = [
  {
    id: 'loc-pune-hq',
    organization_id: DEMO_ORG_ID,
    name: 'Pune Executive HQ & Tech Park',
    city: 'Pune',
    type: 'HQ',
    latitude: 18.5204,
    longitude: 73.8567,
    capacity: 1200,
    status: 'OPERATIONAL',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'loc-pune-wh',
    organization_id: DEMO_ORG_ID,
    name: 'Pune Advanced Assembly Warehouse',
    city: 'Pune',
    type: 'Warehouse',
    latitude: 18.6298,
    longitude: 73.7997,
    capacity: 45000,
    status: 'CRITICAL', // Critical stock risk!
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'loc-mumbai-dc',
    organization_id: DEMO_ORG_ID,
    name: 'Mumbai Port Logistics & Distribution Center',
    city: 'Mumbai',
    type: 'Distribution Center',
    latitude: 18.9438,
    longitude: 72.8354,
    capacity: 85000,
    status: 'OPERATIONAL',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'loc-nashik-wh',
    organization_id: DEMO_ORG_ID,
    name: 'Nashik Strategic Buffer Warehouse',
    city: 'Nashik',
    type: 'Warehouse',
    latitude: 19.9975,
    longitude: 73.7898,
    capacity: 35000,
    status: 'OPERATIONAL',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'loc-delhi-oc',
    organization_id: DEMO_ORG_ID,
    name: 'Delhi Northern Operations Center',
    city: 'Delhi NCR',
    type: 'Office',
    latitude: 28.6139,
    longitude: 77.2090,
    capacity: 600,
    status: 'OPERATIONAL',
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const SEED_PROFILES = [
  {
    id: 'user-admin-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'SysAdmin Commander',
    email: 'admin@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-admin',
    role_code: 'ADMIN' as const,
    department_id: 'dept-operations',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-ceo-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Dr. Vikramaditya Singhania',
    email: 'ceo@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-ceo',
    role_code: 'CEO' as const,
    department_id: 'dept-operations',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-coo-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Elena Rostova',
    email: 'coo@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-coo',
    role_code: 'COO' as const,
    department_id: 'dept-operations',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-cfo-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Marcus Vance',
    email: 'cfo@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-cfo',
    role_code: 'CFO' as const,
    department_id: 'dept-finance',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-ops-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Aarav Deshmukh',
    email: 'ops.manager@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-operations-manager',
    role_code: 'OPERATIONS_MANAGER' as const,
    department_id: 'dept-operations',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-inv-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Pooja Kulkarni',
    email: 'inv.lead@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-inventory-manager',
    role_code: 'INVENTORY_MANAGER' as const,
    department_id: 'dept-inventory',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-proc-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Rajesh Nair',
    email: 'procurement@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-procurement-manager',
    role_code: 'PROCUREMENT_MANAGER' as const,
    department_id: 'dept-procurement',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-hr-01',
    organization_id: DEMO_ORG_ID,
    full_name: 'Ananya Iyer',
    email: 'hr.director@stratiq.enterprise',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=128&auto=format&fit=crop&q=80',
    role_id: 'role-hr-manager',
    role_code: 'HR_MANAGER' as const,
    department_id: 'dept-workforce',
    status: 'ACTIVE' as const,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z',
  },
];

export const SEED_WAREHOUSES: Warehouse[] = [
  {
    id: 'wh-pune-01',
    organization_id: DEMO_ORG_ID,
    location_id: 'loc-pune-wh',
    name: 'Pune Advanced Facility Hub',
    code: 'WH-PUN-01',
    max_capacity: 45000,
    current_capacity: 38200,
    status: 'CRITICAL_STOCK',
  },
  {
    id: 'wh-mumbai-01',
    organization_id: DEMO_ORG_ID,
    location_id: 'loc-mumbai-dc',
    name: 'Mumbai Central Sea Logistics Hub',
    code: 'DC-BOM-01',
    max_capacity: 85000,
    current_capacity: 52000,
    status: 'OPERATIONAL',
  },
  {
    id: 'wh-nashik-01',
    organization_id: DEMO_ORG_ID,
    location_id: 'loc-nashik-wh',
    name: 'Nashik Strategic Buffer Facility',
    code: 'WH-NSK-01',
    max_capacity: 35000,
    current_capacity: 18000,
    status: 'OPERATIONAL',
  },
];

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod-sc-01',
    organization_id: DEMO_ORG_ID,
    sku: 'SKU-SC-9040-X',
    name: 'TX-9 Industrial Microcontroller Unit',
    category: 'Semiconductors',
    unit_price: 3450.00,
    cost_price: 2100.00,
    reorder_point: 400,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-sc-02',
    organization_id: DEMO_ORG_ID,
    sku: 'SKU-OP-4100-PRO',
    name: 'Optical LiDAR Matrix Sensor',
    category: 'Sensors',
    unit_price: 8900.00,
    cost_price: 5400.00,
    reorder_point: 250,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-sc-03',
    organization_id: DEMO_ORG_ID,
    sku: 'SKU-PM-1200-S',
    name: 'Dual-Stage Power Inverter Module',
    category: 'Power Electronics',
    unit_price: 5200.00,
    cost_price: 3200.00,
    reorder_point: 300,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-sc-04',
    organization_id: DEMO_ORG_ID,
    sku: 'SKU-RB-7700-ARM',
    name: '6-Axis Robotic Actuator Core',
    category: 'Robotics',
    unit_price: 18500.00,
    cost_price: 12000.00,
    reorder_point: 100,
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prod-sc-05',
    organization_id: DEMO_ORG_ID,
    sku: 'SKU-CS-3300-HD',
    name: 'Titanium Thermal Heat Sink Assembly',
    category: 'Structural',
    unit_price: 1450.00,
    cost_price: 850.00,
    reorder_point: 600,
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const SEED_INVENTORY: Inventory[] = [
  {
    id: 'inv-001',
    warehouse_id: 'wh-pune-01',
    product_id: 'prod-sc-01', // TX-9 Microcontroller
    current_stock: 42, // CRITICALLY LOW! Minimum is 400!
    minimum_stock: 400,
    maximum_stock: 3000,
    reserved_stock: 285, // Deficit of 243 items!
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-002',
    warehouse_id: 'wh-mumbai-01',
    product_id: 'prod-sc-01',
    current_stock: 1450, // Available stock to transfer!
    minimum_stock: 300,
    maximum_stock: 4000,
    reserved_stock: 120,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-003',
    warehouse_id: 'wh-nashik-01',
    product_id: 'prod-sc-01',
    current_stock: 820,
    minimum_stock: 200,
    maximum_stock: 2500,
    reserved_stock: 80,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-004',
    warehouse_id: 'wh-pune-01',
    product_id: 'prod-sc-02',
    current_stock: 310,
    minimum_stock: 250,
    maximum_stock: 1500,
    reserved_stock: 180,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-005',
    warehouse_id: 'wh-mumbai-01',
    product_id: 'prod-sc-03',
    current_stock: 940,
    minimum_stock: 300,
    maximum_stock: 2000,
    reserved_stock: 95,
    updated_at: new Date().toISOString(),
  },
  {
    id: 'inv-006',
    warehouse_id: 'wh-pune-01',
    product_id: 'prod-sc-04',
    current_stock: 145,
    minimum_stock: 100,
    maximum_stock: 600,
    reserved_stock: 60,
    updated_at: new Date().toISOString(),
  },
];

export const SEED_SUPPLIERS: Supplier[] = [
  {
    id: 'sup-nexus-01',
    organization_id: DEMO_ORG_ID,
    name: 'Nexus Microelectronics Global AG',
    contact_name: 'Klaus Lindner',
    email: 'k.lindner@nexus-ag.com',
    phone: '+49 89 2442 8190',
    rating: 4.85,
    status: 'AT_RISK', // Supplier is experiencing port/freight delay!
    lead_time_days: 7,
  },
  {
    id: 'sup-photon-02',
    organization_id: DEMO_ORG_ID,
    name: 'Photonics Precision Optics Ltd.',
    contact_name: 'Mei-Ling Zhou',
    email: 'orders@photonics-optics.tw',
    phone: '+886 2 2789 3300',
    rating: 4.92,
    status: 'PREFERRED',
    lead_time_days: 5,
  },
  {
    id: 'sup-titan-03',
    organization_id: DEMO_ORG_ID,
    name: 'Titanium Alloys & Aerospace Extrusions',
    contact_name: 'Devraj Kapoor',
    email: 'supply@titanextrusions.in',
    phone: '+91 22 6123 9900',
    rating: 4.70,
    status: 'ACTIVE',
    lead_time_days: 4,
  },
];

export const SEED_PURCHASE_ORDERS: PurchaseOrder[] = [
  {
    id: 'po-8942',
    supplier_id: 'sup-nexus-01',
    created_by: 'user-proc-01',
    status: 'DELAYED',
    total_amount: 4200000.00,
    expected_delivery: '2026-08-21T18:00:00Z', // Expected today, delayed!
    created_at: '2026-08-14T09:30:00Z',
  },
  {
    id: 'po-8943',
    supplier_id: 'sup-photon-02',
    created_by: 'user-proc-01',
    status: 'ORDERED',
    total_amount: 1780000.00,
    expected_delivery: '2026-08-24T12:00:00Z',
    created_at: '2026-08-18T11:00:00Z',
  },
  {
    id: 'po-8944',
    supplier_id: 'sup-titan-03',
    created_by: 'user-proc-01',
    status: 'DELIVERED',
    total_amount: 850000.00,
    expected_delivery: '2026-08-20T16:00:00Z',
    created_at: '2026-08-12T14:15:00Z',
  },
];

export const SEED_DELIVERIES: Delivery[] = [
  {
    id: 'del-po-8942',
    purchase_order_id: 'po-8942',
    status: 'DELAYED',
    expected_date: '2026-08-21T18:00:00Z',
    delay_hours: 48,
    tracking_reference: 'DHL-EXPRESS-99281744-DE',
    created_at: '2026-08-14T10:00:00Z',
    updated_at: '2026-08-21T19:15:00Z',
  },
  {
    id: 'del-po-8943',
    purchase_order_id: 'po-8943',
    status: 'IN_TRANSIT',
    expected_date: '2026-08-24T12:00:00Z',
    delay_hours: 0,
    tracking_reference: 'FEDEX-CARGO-77182901-TW',
    created_at: '2026-08-18T12:00:00Z',
    updated_at: '2026-08-21T14:00:00Z',
  },
];

export const SEED_CUSTOMERS: Customer[] = [
  {
    id: 'cust-tata-01',
    organization_id: DEMO_ORG_ID,
    name: 'Tata Advanced Systems Robotics',
    email: 'procurement@tataadvanced.com',
    phone: '+91 20 6611 2000',
    tier: 'ENTERPRISE',
    address: 'Chakan Industrial Corridor, Pune',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cust-lnt-02',
    organization_id: DEMO_ORG_ID,
    name: 'L&T Heavy Engineering Automation',
    email: 'supplychain@larsentoubro.com',
    phone: '+91 22 6752 5656',
    tier: 'ENTERPRISE',
    address: 'Powai Complex, Mumbai',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'cust-bharat-03',
    organization_id: DEMO_ORG_ID,
    name: 'Bharat Dynamics Defense Systems',
    email: 'contracts@bdl-india.in',
    phone: '+91 40 2345 6789',
    tier: 'ENTERPRISE',
    address: 'Kanchanbagh, Hyderabad',
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const SEED_SALES_ORDERS: SalesOrder[] = [
  {
    id: 'so-901',
    organization_id: DEMO_ORG_ID,
    customer_id: 'cust-tata-01',
    order_number: 'SO-IN-2026-901',
    status: 'PROCESSING',
    total_amount: 380000.00,
    warehouse_id: 'wh-pune-01',
    created_at: '2026-08-20T10:00:00Z',
    updated_at: '2026-08-21T08:00:00Z',
  },
  {
    id: 'so-902',
    organization_id: DEMO_ORG_ID,
    customer_id: 'cust-lnt-02',
    order_number: 'SO-IN-2026-902',
    status: 'PROCESSING',
    total_amount: 290000.00,
    warehouse_id: 'wh-pune-01',
    created_at: '2026-08-20T14:30:00Z',
    updated_at: '2026-08-21T09:00:00Z',
  },
  {
    id: 'so-903',
    organization_id: DEMO_ORG_ID,
    customer_id: 'cust-bharat-03',
    order_number: 'SO-IN-2026-903',
    status: 'CONFIRMED',
    total_amount: 170000.00,
    warehouse_id: 'wh-pune-01',
    created_at: '2026-08-21T07:15:00Z',
    updated_at: '2026-08-21T09:30:00Z',
  },
];

// Requirement 33 & 34: ₹8,40,000 revenue at risk across 243 affected units/orders
export const SEED_SLAS: SLA[] = [
  {
    id: 'sla-inc-01',
    incident_id: 'inc-pune-critical-01',
    duration_minutes: 180,
    // Set deadline to exactly 2h 14m from now to replicate "02:14:28 SLA" from Hackathon prompt!
    deadline: new Date(Date.now() + (2 * 3600 + 14 * 60 + 28) * 1000).toISOString(),
    status: 'WARNING',
    created_at: '2026-08-21T19:44:00Z',
  },
  {
    id: 'sla-inc-02',
    incident_id: 'inc-mumbai-02',
    duration_minutes: 360,
    deadline: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    status: 'ACTIVE',
    created_at: '2026-08-21T15:00:00Z',
  },
];

export const SEED_INCIDENTS: Incident[] = [
  {
    id: 'inc-pune-critical-01',
    organization_id: DEMO_ORG_ID,
    incident_number: 'INC-2026-0842',
    title: 'Pune Warehouse: Semiconductor Stockout from Supplier Port Delay',
    description: 'PO #8942 (TX-9 Microcontroller Units) delayed by 48 hours at Frankfurt customs transit. Pune facility current stock (42 units) cannot fulfill 243 committed customer orders.',
    priority: 'CRITICAL',
    status: 'ACTION_REQUIRED',
    department_id: 'dept-operations',
    location_id: 'loc-pune-wh',
    owner_id: 'user-ops-01',
    impact: 'Assembly line halt in 6 hours if buffer stock is not routed from Mumbai DC.',
    affected_orders: 243,
    revenue_impact: 840000.00, // ₹8,40,000 (₹8.4L)
    sla_id: 'sla-inc-01',
    created_at: '2026-08-21T19:44:00Z',
    updated_at: '2026-08-21T20:10:00Z',
  },
  {
    id: 'inc-mumbai-02',
    organization_id: DEMO_ORG_ID,
    incident_number: 'INC-2026-0839',
    title: 'Mumbai Logistics: Dock Bay 4 Conveyor Belt Thermal Sensor Tripped',
    description: 'Automated conveyor sensor triggered overtemperature safety lock during high-throughput pallet loading.',
    priority: 'MEDIUM',
    status: 'INVESTIGATING',
    department_id: 'dept-inventory',
    location_id: 'loc-mumbai-dc',
    owner_id: 'user-inv-01',
    impact: 'Cargo throughput reduced by 15% on Bay 4.',
    affected_orders: 18,
    revenue_impact: 65000.00,
    sla_id: 'sla-inc-02',
    created_at: '2026-08-21T15:00:00Z',
    updated_at: '2026-08-21T16:30:00Z',
  },
];

export const SEED_COMMENTS: IncidentComment[] = [
  {
    id: 'com-001',
    incident_id: 'inc-pune-critical-01',
    user_id: 'user-ops-01',
    comment: 'Automation detected DHL tracking delay for PO-8942. Confirmed Pune inventory deficit of 243 units against SO-901, SO-902, and SO-903.',
    created_at: '2026-08-21T19:45:00Z',
  },
  {
    id: 'com-002',
    incident_id: 'inc-pune-critical-01',
    user_id: 'user-coo-01',
    comment: 'Mumbai DC has 1,450 units of TX-9. Preparing expedited express transfer request of 300 units via Pune expressway corridor.',
    created_at: '2026-08-21T19:52:00Z',
  },
];

export const SEED_APPROVALS: Approval[] = [
  {
    id: 'appr-trf-001',
    organization_id: DEMO_ORG_ID,
    entity_type: 'INVENTORY_TRANSFER',
    entity_id: 'trf-mb-pun-001',
    requester_id: 'user-ops-01',
    approver_id: 'user-coo-01',
    step: 1,
    total_steps: 2,
    status: 'PENDING',
    amount: 1035000.00,
    comments: 'Emergency inter-facility stock transfer of 300x TX-9 Microcontrollers from Mumbai DC to Pune Hub to mitigate INC-2026-0842.',
    created_at: '2026-08-21T20:00:00Z',
    updated_at: '2026-08-21T20:00:00Z',
  },
  {
    id: 'appr-po-002',
    organization_id: DEMO_ORG_ID,
    entity_type: 'PURCHASE_ORDER',
    entity_id: 'po-8945',
    requester_id: 'user-proc-01',
    approver_id: 'user-cfo-01',
    step: 2,
    total_steps: 3,
    status: 'PENDING',
    amount: 2850000.00,
    comments: 'Q4 Fiber Optic Harness procurement expansion.',
    created_at: '2026-08-21T16:00:00Z',
    updated_at: '2026-08-21T16:00:00Z',
  },
];

export const SEED_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-001',
    user_id: 'user-ceo-01',
    organization_id: DEMO_ORG_ID,
    type: 'INCIDENT',
    severity: 'CRITICAL',
    title: 'CRITICAL: Semiconductor Stockout at Pune Warehouse',
    message: '243 customer orders affected. ₹8.4L revenue at risk. 02:14:28 SLA countdown active.',
    entity_type: 'incidents',
    entity_id: 'inc-pune-critical-01',
    is_read: false,
    created_at: '2026-08-21T19:44:00Z',
  },
  {
    id: 'notif-002',
    user_id: 'user-coo-01',
    organization_id: DEMO_ORG_ID,
    type: 'APPROVAL',
    severity: 'WARNING',
    title: 'Action Required: Emergency Stock Transfer Approval',
    message: 'Aarav Deshmukh requested transfer of 300 units from Mumbai DC to Pune WH.',
    entity_type: 'approvals',
    entity_id: 'appr-trf-001',
    is_read: false,
    created_at: '2026-08-21T20:00:00Z',
  },
  {
    id: 'notif-003',
    user_id: 'user-ops-01',
    organization_id: DEMO_ORG_ID,
    type: 'SUPPLIER_DELAY',
    severity: 'CRITICAL',
    title: 'Nexus AG: PO-8942 Delivery Delayed (+48 Hours)',
    message: 'Flight connection missed in Frankfurt. New ETA: Aug 23, 2026.',
    entity_type: 'deliveries',
    entity_id: 'del-po-8942',
    is_read: true,
    created_at: '2026-08-21T19:15:00Z',
  },
];

export const SEED_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    organization_id: DEMO_ORG_ID,
    user_id: 'user-proc-01',
    action: 'SUPPLIER_DELAY_RECORDED',
    entity_type: 'DELIVERY',
    entity_id: 'del-po-8942',
    previous_state: { status: 'IN_TRANSIT', delay_hours: 0 },
    new_state: { status: 'DELAYED', delay_hours: 48 },
    metadata: { tracking: 'DHL-EXPRESS-99281744-DE', supplier: 'Nexus Microelectronics AG' },
    created_at: '2026-08-21T19:15:00Z',
  },
  {
    id: 'aud-002',
    organization_id: DEMO_ORG_ID,
    user_id: 'user-ops-01',
    action: 'INCIDENT_AUTO_CREATED',
    entity_type: 'INCIDENT',
    entity_id: 'inc-pune-critical-01',
    previous_state: null,
    new_state: { priority: 'CRITICAL', affected_orders: 243, revenue_impact: 840000 },
    metadata: { rule: 'SUPPLIER_DELAY_IMPACT_ANALYZER_V3' },
    created_at: '2026-08-21T19:44:00Z',
  },
  {
    id: 'aud-003',
    organization_id: DEMO_ORG_ID,
    user_id: 'user-coo-01',
    action: 'APPROVAL_REQUEST_SUBMITTED',
    entity_type: 'APPROVAL',
    entity_id: 'appr-trf-001',
    previous_state: null,
    new_state: { status: 'PENDING', step: 1 },
    metadata: { source: 'DC-BOM-01', destination: 'WH-PUN-01', quantity: 300 },
    created_at: '2026-08-21T20:00:00Z',
  },
];

export const SEED_ENTERPRISE_METRICS: EnterpriseMetric = {
  id: 'met-001',
  organization_id: DEMO_ORG_ID,
  metric_date: '2026-08-21',
  revenue: 148500000.00,
  expenses: 92400000.00,
  orders: 1420,
  inventory_health: 78.4,
  workforce_availability: 96.5,
  critical_incidents: 1,
  enterprise_health: 84.2, // 0-100 score
  created_at: new Date().toISOString(),
};
