import React, { useState } from 'react';
import { 
  BarChart3, Download, FileText, Calendar, Filter, 
  CheckCircle2, Printer, ArrowDownToLine 
} from 'lucide-react';
import { useRealtime } from '../../context/RealtimeContext';
import { useAuth } from '../../context/AuthContext';

export const ReportGenerator: React.FC = () => {
  const { metrics, incidents, inventory } = useRealtime();
  const { user } = useAuth();
  const [reportType, setReportType] = useState<'EXECUTIVE' | 'INCIDENT' | 'INVENTORY'>('EXECUTIVE');
  const [isExported, setIsExported] = useState(false);

  const handleExportCSV = () => {
    const csvContent = "data:text/csv;charset=utf-8," + 
      "Metric,Value\n" + 
      `Enterprise Health,${metrics.enterprise_health}%\n` + 
      `Inventory Health,${metrics.inventory_health}%\n` + 
      `Critical Incidents,${metrics.critical_incidents}\n` + 
      `Workforce Availability,${metrics.workforce_availability}%\n` + 
      `Revenue At Risk,₹8.4L\n` + 
      `Generated At,${new Date().toISOString()}`;
    
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `STRATIQ_${reportType}_REPORT_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    setIsExported(true);
    setTimeout(() => setIsExported(false), 3000);
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-white/10">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-[11px] font-mono text-amber-400 uppercase tracking-wider font-semibold">
              Deterministic Database Aggregations
            </span>
            <span className="h-1 w-1 rounded-full bg-neutral-600"></span>
            <span className="text-[11px] text-neutral-400">PostgreSQL Reports Table</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white mt-1 font-editorial">
            Executive Operations Reports
          </h1>
        </div>

        <div className="flex items-center gap-2.5">
          <button
            onClick={handleExportCSV}
            className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-amber-500 hover:bg-amber-400 text-neutral-950 font-bold text-xs transition-all shadow-lg shadow-amber-500/20"
          >
            <Download className="h-3.5 w-3.5" />
            <span>{isExported ? 'Report Downloaded!' : 'Export CSV / Data'}</span>
          </button>
        </div>
      </div>

      {/* Report Type Selector */}
      <div className="flex items-center gap-2 border-b border-white/10 text-xs">
        {[
          { id: 'EXECUTIVE', label: 'Executive Command Summary' },
          { id: 'INCIDENT', label: 'Incident & SLA Post-Mortem' },
          { id: 'INVENTORY', label: 'Warehouse Stock & Buffer Audit' },
        ].map(r => (
          <button
            key={r.id}
            onClick={() => setReportType(r.id as any)}
            className={`px-4 py-2 border-b-2 transition-all font-medium ${
              reportType === r.id
                ? 'border-amber-400 text-amber-300 font-bold'
                : 'border-transparent text-neutral-400 hover:text-neutral-200'
            }`}
          >
            {r.label}
          </button>
        ))}
      </div>

      {/* Report Document Sheet (Clean, Editorial, High-Contrast) */}
      <div className="glass-panel p-6 sm:p-8 rounded-2xl border border-white/15 bg-neutral-900/90 space-y-6 max-w-4xl mx-auto shadow-2xl">
        
        {/* Document Header */}
        <div className="flex justify-between items-start pb-6 border-b border-white/10">
          <div>
            <div className="text-[10px] font-mono uppercase text-amber-400 tracking-widest">
              STRATIQ ENTERPRISE REPORT • CONFIDENTIAL
            </div>
            <h2 className="text-xl sm:text-2xl font-bold text-white mt-1 font-editorial">
              {reportType === 'EXECUTIVE' && 'Operational Health & Financial Risk Summary'}
              {reportType === 'INCIDENT' && 'Supply Chain Blocker & SLA Root Cause Audit'}
              {reportType === 'INVENTORY' && 'Multi-Facility Inventory & Buffer Variance'}
            </h2>
            <div className="text-xs text-neutral-400 mt-1">
              Generated by: <strong>{user?.full_name}</strong> • Scope: Apex Semiconductor Ltd.
            </div>
          </div>
          <div className="text-right text-xs font-mono text-neutral-400">
            <div>Date: {new Date().toLocaleDateString()}</div>
            <div>Status: VERIFIED</div>
          </div>
        </div>

        {/* Executive Highlights Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 rounded-xl bg-neutral-950/70 border border-white/10 space-y-1">
            <span className="text-[10px] font-mono uppercase text-neutral-400">Enterprise Health Index</span>
            <div className="text-2xl font-bold font-mono text-emerald-400">{metrics.enterprise_health}%</div>
            <span className="text-[10px] text-neutral-400">Formula weight applied</span>
          </div>

          <div className="p-4 rounded-xl bg-neutral-950/70 border border-white/10 space-y-1">
            <span className="text-[10px] font-mono uppercase text-neutral-400">Active Critical Exposures</span>
            <div className="text-2xl font-bold font-mono text-rose-400">{metrics.critical_incidents} Incidents</div>
            <span className="text-[10px] text-neutral-400">Pune Warehouse deficit</span>
          </div>

          <div className="p-4 rounded-xl bg-neutral-950/70 border border-white/10 space-y-1">
            <span className="text-[10px] font-mono uppercase text-neutral-400">Revenue Risk Factor</span>
            <div className="text-2xl font-bold font-mono text-white">₹8.4L</div>
            <span className="text-[10px] text-neutral-400">243 committed orders</span>
          </div>
        </div>

        {/* Section Body */}
        <div className="space-y-3 text-xs text-neutral-300 leading-relaxed">
          <h4 className="font-bold text-white uppercase font-mono tracking-wider text-xs">
            1. Tactical Findings & Root Cause
          </h4>
          <p>
            Automated monitoring detected a 48-hour flight connection delay on PO #8942 (DHL-EXPRESS-99281744-DE) originating from Frankfurt customs hub. As a result, the Pune Assembly Facility reached a critical deficit on TX-9 Microcontrollers (42 current stock vs 400 minimum threshold).
          </p>
          <p>
            Mitigation protocol was successfully queued: 300 units dispatched from Mumbai Port Logistics Hub via expedited expressway transit to restore fulfillment capability for 243 active customer orders.
          </p>
        </div>

        {/* Signature & Verification Block */}
        <div className="pt-6 border-t border-white/10 flex items-center justify-between text-xs text-neutral-400">
          <div className="flex items-center gap-2">
            <CheckCircle2 className="h-4 w-4 text-emerald-400" />
            <span>Database Integrity & RLS Signoff Confirmed</span>
          </div>
          <div className="font-mono text-[10px]">
            SHA-256: 8f9b...3c12
          </div>
        </div>

      </div>

    </div>
  );
};
